import JoltBytecode.JoltISA.Instruction
import JoltBytecode.JoltISA.VirtualRegisters
import JoltBytecode.JoltISA.Expansions.ALU

/-!
# Auto-generated Jolt-ISA expansion programs

Generated by `jolt-lean-gen --lean` from the Rust bytecode expander
(`expand_instruction`), the source of truth. Do not edit by hand;
regenerate instead. Each `…ProgramAuto` mirrors the hand-written
`…Program` in `JoltISA/Expansions/`; `if isX0 rd` shows both arms of
the rd==x0 branch. Immediate helpers come from `Expansions.ALU`.
-/

open Sail PreSail LeanRV64D.Functions

namespace JoltISA

/-- Auto-generated from the Rust `DIV` expansion. -/
def divProgramAuto (rd rs1 rs2 : regidx) (advice0 advice1 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (inlineTmp 0)) advice0) <|
    .instr (.VirtualAdvice (.vreg (inlineTmp 1)) advice1) <|
    .instr (.VirtualAssertValidDiv0 (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualChangeDivisor (.vreg (inlineTmp 2)) (.xreg rs1) (.xreg rs2)) <|
    .instr (.VirtualMovsign (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualMovsign (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 0))) <|
    .instr (.MULHU (.vreg (inlineTmp 6)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.ADD (.vreg (inlineTmp 6)) (.vreg (inlineTmp 6)) (.vreg (inlineTmp 4))) <|
    .instr (.ADD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4)) (sraiBitmask 63)) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5)) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 3)) (.xreg rs1) (sraiBitmask 63)) <|
    .instr (.XOR (.vreg (inlineTmp 5)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.SUB (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.ADD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 4)) (.xreg rs1) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (sraiBitmask 63)) <|
    .instr (.XOR (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.SUB (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (inlineTmp 1)) (.vreg (inlineTmp 5))) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `DIVU` expansion. -/
def divuProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (inlineTmp 0)) advice0) <|
    .instr (.VirtualAssertValidDiv0 (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.VirtualAssertLTE (.vreg (inlineTmp 1)) (.xreg rs1)) <|
    .instr (.SUB (.vreg (inlineTmp 1)) (.xreg rs1) (.vreg (inlineTmp 1))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LB` expansion. -/
def lbProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.ADDI (.vreg (inlineTmp 1)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (7 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 3)) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (sraiBitmask 56)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.ADDI (.vreg (inlineTmp 0)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (7 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRAI (.xreg rd) (.vreg (inlineTmp 1)) (sraiBitmask 56)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LBU` expansion. -/
def lbuProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.ADDI (.vreg (inlineTmp 1)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (7 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 3)) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (srliBitmask 56)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.ADDI (.vreg (inlineTmp 0)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (7 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRLI (.xreg rd) (.vreg (inlineTmp 1)) (srliBitmask 56)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LH` expansion. -/
def lhProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.ADDI (.vreg (inlineTmp 1)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (6 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 3)) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (sraiBitmask 48)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (6 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRAI (.xreg rd) (.vreg (inlineTmp 1)) (sraiBitmask 48)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LHU` expansion. -/
def lhuProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.ADDI (.vreg (inlineTmp 1)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (6 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 3)) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (srliBitmask 48)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (6 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRLI (.xreg rd) (.vreg (inlineTmp 1)) (srliBitmask 48)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LW` expansion. -/
def lwProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.ADDI (.vreg (inlineTmp 1)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 3)) (.vreg (inlineTmp 1))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `MULH` expansion. -/
def mulhProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMovsign (.vreg (inlineTmp 0)) (.xreg rs1)) <|
    .instr (.VirtualMovsign (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.xreg rs1)) <|
    .instr (.MULHU (.vreg (inlineTmp 2)) (.xreg rs1) (.xreg rs2)) <|
    .instr (.ADD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.ADD (.xreg rd) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `MULHSU` expansion. -/
def mulhsuProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMovsign (.vreg (inlineTmp 0)) (.xreg rs1)) <|
    .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (1 : BitVec 12)) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.xreg rs1) (.vreg (inlineTmp 0))) <|
    .instr (.ADD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.MULHU (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.xreg rs2)) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.ADD (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.SLTU (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.ADD (.xreg rd) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `REM` expansion. -/
def remProgramAuto (rd rs1 rs2 : regidx) (advice0 advice1 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (inlineTmp 0)) advice0) <|
    .instr (.VirtualAdvice (.vreg (inlineTmp 1)) advice1) <|
    .instr (.VirtualAssertValidDiv0 (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualChangeDivisor (.vreg (inlineTmp 2)) (.xreg rs1) (.xreg rs2)) <|
    .instr (.VirtualMovsign (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualMovsign (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 0))) <|
    .instr (.MULHU (.vreg (inlineTmp 6)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.ADD (.vreg (inlineTmp 6)) (.vreg (inlineTmp 6)) (.vreg (inlineTmp 4))) <|
    .instr (.ADD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4)) (sraiBitmask 63)) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5)) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 3)) (.xreg rs1) (sraiBitmask 63)) <|
    .instr (.XOR (.vreg (inlineTmp 5)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.SUB (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.ADD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 4)) (.xreg rs1) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (sraiBitmask 63)) <|
    .instr (.XOR (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.SUB (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (inlineTmp 1)) (.vreg (inlineTmp 4))) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 5)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `REMU` expansion. -/
def remuProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (inlineTmp 0)) advice0) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.VirtualAssertLTE (.vreg (inlineTmp 0)) (.xreg rs1)) <|
    .instr (.SUB (.vreg (inlineTmp 0)) (.xreg rs1) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SB` expansion. -/
def sbProgramAuto (rs1 rs2 : regidx) (imm : BitVec 12) : Program :=
  .instr (.ADDI (.vreg (inlineTmp 0)) (.xreg rs1) imm) <|
  .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (-8 : BitVec 12)) <|
  .instr (.LD .normal (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
  .instr (.VirtualMULI (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0)) (slliMultiplier 3)) <|
  .instr (.LUI (.vreg (inlineTmp 0)) (255 : BitVec 64)) <|
  .instr (.VirtualPow2 (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
  .instr (.MUL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 4))) <|
  .instr (.VirtualPow2 (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
  .instr (.MUL (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 4))) <|
  .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
  .instr (.AND (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
  .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
  .instr (.SD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
  .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SH` expansion. -/
def shProgramAuto (rs1 rs2 : regidx) (imm : BitVec 12) : Program :=
  .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_SAMO_Addr_Align ())) <|
  .instr (.ADDI (.vreg (inlineTmp 0)) (.xreg rs1) imm) <|
  .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (-8 : BitVec 12)) <|
  .instr (.LD .normal (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
  .instr (.VirtualMULI (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0)) (slliMultiplier 3)) <|
  .instr (.LUI (.vreg (inlineTmp 0)) (65535 : BitVec 64)) <|
  .instr (.VirtualPow2 (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
  .instr (.MUL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 4))) <|
  .instr (.VirtualPow2 (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
  .instr (.MUL (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 4))) <|
  .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
  .instr (.AND (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
  .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
  .instr (.SD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
  .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SLL` expansion. -/
def sllProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualPow2 (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.MUL (.xreg rd) (.xreg rs1) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SLLI` expansion. -/
def slliProgramAuto (rd rs1 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMULI (.xreg rd) (.xreg rs1) (slliMultiplier 37)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRA` expansion. -/
def sraProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.VirtualSRA (.xreg rd) (.xreg rs1) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRAI` expansion. -/
def sraiProgramAuto (rd rs1 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSRAI (.xreg rd) (.xreg rs1) (sraiBitmask 37)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRL` expansion. -/
def srlProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.VirtualSRL (.xreg rd) (.xreg rs1) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRLI` expansion. -/
def srliProgramAuto (rd rs1 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSRLI (.xreg rd) (.xreg rs1) (srliBitmask 37)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SW` expansion. -/
def swProgramAuto (rs1 rs2 : regidx) (imm : BitVec 12) : Program :=
  .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_SAMO_Addr_Align ())) <|
  .instr (.ADDI (.vreg (inlineTmp 0)) (.xreg rs1) imm) <|
  .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (-8 : BitVec 12)) <|
  .instr (.LD .normal (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
  .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 3)) <|
  .instr (.ORI (.vreg (inlineTmp 3)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
  .instr (.VirtualSRLI (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (srliBitmask 32)) <|
  .instr (.VirtualPow2 (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0))) <|
  .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
  .instr (.VirtualPow2 (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0))) <|
  .instr (.MUL (.vreg (inlineTmp 0)) (.xreg rs2) (.vreg (inlineTmp 4))) <|
  .instr (.XOR (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
  .instr (.AND (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 3))) <|
  .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
  .instr (.SD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
  .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `ADDIW` expansion. -/
def addiwProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.ADDI (.xreg rd) (.xreg rs1) imm) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SLLIW` expansion. -/
def slliwProgramAuto (rd rs1 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMULI (.xreg rd) (.xreg rs1) (slliMultiplier 5)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRLIW` expansion. -/
def srliwProgramAuto (rd rs1 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.xreg rs1) (slliMultiplier 32)) <|
    .instr (.VirtualSRLI (.xreg rd) (.vreg (inlineTmp 0)) (srliBitmask 37)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRAIW` expansion. -/
def sraiwProgramAuto (rd rs1 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.xreg rs1)) <|
    .instr (.VirtualSRAI (.xreg rd) (.vreg (inlineTmp 0)) (sraiBitmask 5)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `ADDW` expansion. -/
def addwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.ADD (.xreg rd) (.xreg rs1) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SUBW` expansion. -/
def subwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.SUB (.xreg rd) (.xreg rs1) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SLLW` expansion. -/
def sllwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualPow2W (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.MUL (.xreg rd) (.xreg rs1) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRLW` expansion. -/
def srlwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMULI (.vreg (inlineTmp 1)) (.xreg rs1) (slliMultiplier 32)) <|
    .instr (.ORI (.vreg (inlineTmp 0)) (.xreg rs2) (32 : BitVec 12)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualSRL (.xreg rd) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRAW` expansion. -/
def srawProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.xreg rs1)) <|
    .instr (.ANDI (.vreg (inlineTmp 1)) (.xreg rs2) (31 : BitVec 12)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1))) <|
    .instr (.VirtualSRA (.xreg rd) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1))) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LWU` expansion. -/
def lwuProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.ADDI (.vreg (inlineTmp 1)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (4 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 3)) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (srliBitmask 32)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.xreg rs1) imm) <|
    .instr (.ANDI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (-8 : BitVec 12)) <|
    .instr (.LD .normal (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.XORI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (4 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 3)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRLI (.xreg rd) (.vreg (inlineTmp 1)) (srliBitmask 32)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `DIVUW` expansion. -/
def divuwProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 0)) (.xreg rs1)) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.VirtualAdvice (.vreg (inlineTmp 2)) advice0) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.VirtualAssertLTE (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (inlineTmp 3)) (.vreg (inlineTmp 1))) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualAssertValidDiv0 (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `DIVW` expansion. -/
def divwProgramAuto (rd rs1 rs2 : regidx) (advice0 advice1 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (inlineTmp 0)) advice0) <|
    .instr (.VirtualAdvice (.vreg (inlineTmp 1)) advice1) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 6)) (.xreg rs1)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 5)) (.xreg rs2)) <|
    .instr (.VirtualAssertValidDiv0 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualChangeDivisorW (.vreg (inlineTmp 2)) (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0)) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (sraiBitmask 32)) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 4)) (.xreg (regidx.Regidx 0)) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6)) (sraiBitmask 31)) <|
    .instr (.XOR (.vreg (inlineTmp 5)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 4))) <|
    .instr (.SUB (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.ADD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 3)) (.vreg (inlineTmp 6)) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2)) (sraiBitmask 31)) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `MULW` expansion. -/
def mulwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.MUL (.xreg rd) (.xreg rs1) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.xreg rd)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `REMUW` expansion. -/
def remuwProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 0)) (.xreg rs1)) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.VirtualAdvice (.vreg (inlineTmp 2)) advice0) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.VirtualAssertLTE (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.SUB (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 2))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `REMW` expansion. -/
def remwProgramAuto (rd rs1 rs2 : regidx) (advice0 advice1 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (inlineTmp 0)) advice0) <|
    .instr (.VirtualAdvice (.vreg (inlineTmp 1)) advice1) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 6)) (.xreg rs1)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 5)) (.xreg rs2)) <|
    .instr (.VirtualAssertValidDiv0 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualChangeDivisorW (.vreg (inlineTmp 2)) (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0)) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (sraiBitmask 32)) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 4)) (.xreg (regidx.Regidx 0)) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6)) (sraiBitmask 31)) <|
    .instr (.XOR (.vreg (inlineTmp 5)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 4))) <|
    .instr (.SUB (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.ADD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualAssertEQ (.vreg (inlineTmp 3)) (.vreg (inlineTmp 6)) (0 : BitVec 13)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2)) (sraiBitmask 31)) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 5))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOSWAPW` expansion. -/
def amoswapwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 3)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 3)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 5))) <|
    .instr (.ORI (.vreg (inlineTmp 1)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.AND (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 1))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.ANDI (.vreg (inlineTmp 1)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 4))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 2)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 4))) <|
    .instr (.ORI (.vreg (inlineTmp 0)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.xreg rs2) (.vreg (inlineTmp 4))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.AND (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 0))) <|
    .instr (.XOR (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.ANDI (.vreg (inlineTmp 0)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 3))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOADDW` expansion. -/
def amoaddwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 5)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 5)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6))) <|
    .instr (.ADD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (inlineTmp 3)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 6))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 6))) <|
    .instr (.XOR (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.AND (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.XOR (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.ANDI (.vreg (inlineTmp 3)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 4)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 4)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.ADD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (inlineTmp 2)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.AND (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2))) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOANDW` expansion. -/
def amoandwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 5)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 5)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6))) <|
    .instr (.AND (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (inlineTmp 3)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 6))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 6))) <|
    .instr (.XOR (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.AND (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.XOR (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.ANDI (.vreg (inlineTmp 3)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 4)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 4)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.AND (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (inlineTmp 2)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.AND (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2))) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOORW` expansion. -/
def amoorwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 5)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 5)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6))) <|
    .instr (.OR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (inlineTmp 3)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 6))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 6))) <|
    .instr (.XOR (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.AND (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.XOR (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.ANDI (.vreg (inlineTmp 3)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 4)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 4)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.OR (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (inlineTmp 2)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.AND (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2))) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOXORW` expansion. -/
def amoxorwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 5)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 5)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (inlineTmp 3)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 6))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 5))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 6))) <|
    .instr (.XOR (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.AND (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 3))) <|
    .instr (.XOR (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.ANDI (.vreg (inlineTmp 3)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 4)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 4)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (inlineTmp 2)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.AND (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 2))) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMINW` expansion. -/
def amominwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 3)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 3)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 4)) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 5)) (.vreg (inlineTmp 1))) <|
    .instr (.SLT (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.SUB (.vreg (inlineTmp 4)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.ADD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1))) <|
    .instr (.ORI (.vreg (inlineTmp 5)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 6))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6))) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.AND (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.ANDI (.vreg (inlineTmp 5)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 2)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 3)) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0))) <|
    .instr (.SLT (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.ADD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
    .instr (.ORI (.vreg (inlineTmp 4)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.AND (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.XOR (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.ANDI (.vreg (inlineTmp 4)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMAXW` expansion. -/
def amomaxwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 3)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 3)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 4)) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 5)) (.vreg (inlineTmp 1))) <|
    .instr (.SLT (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.SUB (.vreg (inlineTmp 4)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.ADD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1))) <|
    .instr (.ORI (.vreg (inlineTmp 5)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 6))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6))) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.AND (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.ANDI (.vreg (inlineTmp 5)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 2)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 3)) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0))) <|
    .instr (.SLT (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.ADD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
    .instr (.ORI (.vreg (inlineTmp 4)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.AND (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.XOR (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.ANDI (.vreg (inlineTmp 4)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMINUW` expansion. -/
def amominuwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 3)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 3)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 4)) (.xreg rs2)) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 5)) (.vreg (inlineTmp 1))) <|
    .instr (.SLTU (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.SUB (.vreg (inlineTmp 4)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.ADD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1))) <|
    .instr (.ORI (.vreg (inlineTmp 5)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 6))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6))) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.AND (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.ANDI (.vreg (inlineTmp 5)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 2)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 3)) (.xreg rs2)) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0))) <|
    .instr (.SLTU (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.ADD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
    .instr (.ORI (.vreg (inlineTmp 4)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.AND (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.XOR (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.ANDI (.vreg (inlineTmp 4)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMAXUW` expansion. -/
def amomaxuwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 3)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 3)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 4)) (.xreg rs2)) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 5)) (.vreg (inlineTmp 1))) <|
    .instr (.SLTU (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 4))) <|
    .instr (.SUB (.vreg (inlineTmp 4)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.ADD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1))) <|
    .instr (.ORI (.vreg (inlineTmp 5)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 5)) (.vreg (inlineTmp 5)) (.vreg (inlineTmp 6))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 6)) (.vreg (inlineTmp 3))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 6))) <|
    .instr (.XOR (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.AND (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3))) <|
    .instr (.ANDI (.vreg (inlineTmp 5)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (inlineTmp 2)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 2)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2))) <|
    .instr (.VirtualSRL (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 3)) (.xreg rs2)) <|
    .instr (.VirtualZeroExtendWord (.vreg (inlineTmp 4)) (.vreg (inlineTmp 0))) <|
    .instr (.SLTU (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 3))) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 4))) <|
    .instr (.ADD (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 0))) <|
    .instr (.ORI (.vreg (inlineTmp 4)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 4)) (.vreg (inlineTmp 4)) (.vreg (inlineTmp 5))) <|
    .instr (.VirtualPow2 (.vreg (inlineTmp 5)) (.vreg (inlineTmp 2))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 5))) <|
    .instr (.XOR (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.AND (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 4))) <|
    .instr (.XOR (.vreg (inlineTmp 1)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2))) <|
    .instr (.ANDI (.vreg (inlineTmp 4)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (inlineTmp 4)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (inlineTmp 0))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOSWAPD` expansion. -/
def amoswapdProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SD (.xreg rs1) (.xreg rs2) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (inlineTmp 0)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SD (.xreg rs1) (.xreg rs2) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOADDD` expansion. -/
def amoadddProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (inlineTmp 2)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.ADD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.ADD (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOANDD` expansion. -/
def amoanddProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (inlineTmp 2)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.AND (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.AND (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOORD` expansion. -/
def amoordProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (inlineTmp 2)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.OR (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.OR (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOXORD` expansion. -/
def amoxordProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (inlineTmp 2)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.XOR (.vreg (inlineTmp 1)) (.vreg (inlineTmp 2)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.XOR (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMIND` expansion. -/
def amomindProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLT (.vreg (inlineTmp 2)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2))) <|
    .instr (.ADD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (inlineTmp 0)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLT (.vreg (inlineTmp 1)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.SUB (.vreg (inlineTmp 2)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.ADD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMAXD` expansion. -/
def amomaxdProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLT (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2))) <|
    .instr (.ADD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (inlineTmp 0)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLT (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.SUB (.vreg (inlineTmp 2)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.ADD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMINUD` expansion. -/
def amominudProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLTU (.vreg (inlineTmp 2)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2))) <|
    .instr (.ADD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (inlineTmp 0)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLTU (.vreg (inlineTmp 1)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.SUB (.vreg (inlineTmp 2)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.ADD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMAXUD` expansion. -/
def amomaxudProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (inlineTmp 1)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLTU (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.xreg rs2)) <|
    .instr (.SUB (.vreg (inlineTmp 3)) (.xreg rs2) (.vreg (inlineTmp 1))) <|
    .instr (.MUL (.vreg (inlineTmp 3)) (.vreg (inlineTmp 3)) (.vreg (inlineTmp 2))) <|
    .instr (.ADD (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1)) (.vreg (inlineTmp 3))) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 2)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (inlineTmp 0)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLTU (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.xreg rs2)) <|
    .instr (.SUB (.vreg (inlineTmp 2)) (.xreg rs2) (.vreg (inlineTmp 0))) <|
    .instr (.MUL (.vreg (inlineTmp 2)) (.vreg (inlineTmp 2)) (.vreg (inlineTmp 1))) <|
    .instr (.ADD (.vreg (inlineTmp 1)) (.vreg (inlineTmp 0)) (.vreg (inlineTmp 2))) <|
    .instr (.SD (.xreg rs1) (.vreg (inlineTmp 1)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (inlineTmp 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AdviceLB` expansion. -/
def advicelbProgramAuto (rd : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.VirtualAdviceLoad (.vreg (inlineTmp 0)) advice0) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 56)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (sraiBitmask 56)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdviceLoad (.xreg rd) advice0) <|
    .instr (.VirtualMULI (.xreg rd) (.xreg rd) (slliMultiplier 56)) <|
    .instr (.VirtualSRAI (.xreg rd) (.xreg rd) (sraiBitmask 56)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AdviceLD` expansion. -/
def adviceldProgramAuto (rd : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.VirtualAdviceLoad (.vreg (inlineTmp 0)) advice0) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdviceLoad (.xreg rd) advice0) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AdviceLH` expansion. -/
def advicelhProgramAuto (rd : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.VirtualAdviceLoad (.vreg (inlineTmp 0)) advice0) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 48)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (sraiBitmask 48)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdviceLoad (.xreg rd) advice0) <|
    .instr (.VirtualMULI (.xreg rd) (.xreg rd) (slliMultiplier 48)) <|
    .instr (.VirtualSRAI (.xreg rd) (.xreg rd) (sraiBitmask 48)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AdviceLW` expansion. -/
def advicelwProgramAuto (rd : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.VirtualAdviceLoad (.vreg (inlineTmp 0)) advice0) <|
    .instr (.VirtualMULI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (slliMultiplier 32)) <|
    .instr (.VirtualSRAI (.vreg (inlineTmp 0)) (.vreg (inlineTmp 0)) (sraiBitmask 32)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdviceLoad (.xreg rd) advice0) <|
    .instr (.VirtualMULI (.xreg rd) (.xreg rd) (slliMultiplier 32)) <|
    .instr (.VirtualSRAI (.xreg rd) (.xreg rd) (sraiBitmask 32)) <|
    .done RETIRE_SUCCESS

end JoltISA

-- generated 57 expansion program(s)
