import JoltBytecode.JoltISA.Instruction
import JoltBytecode.JoltISA.VirtualRegisters
import JoltBytecode.JoltISA.Expansions.ALU

/-!
# Auto-generated Jolt-ISA expansion programs

Generated by `jolt-lean-gen --lean` from the Rust bytecode expander
(`expand_instruction`), the source of truth. Do not edit by hand;
regenerate instead. Each `...ProgramAuto` mirrors the final Jolt rows
emitted by Rust for its source instruction parameters.
-/

open Sail PreSail LeanRV64D.Functions

namespace JoltISA

/-- Auto-generated from the Rust `DIV` expansion. -/
def divProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (BitVec.ofNat 7 40)) advice0) <|
    .instr (.VirtualAssertValidDiv0 (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (.xreg rs1)) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 42)) (.xreg rs2) (.xreg rs2)) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (.xreg rs2)) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualAssertLTE (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `DIVU` expansion. -/
def divuProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (BitVec.ofNat 7 40)) advice0) <|
    .instr (.VirtualAssertValidDiv0 (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.VirtualAssertLTE (.vreg (BitVec.ofNat 7 41)) (.xreg rs1)) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LB` expansion. -/
def lbProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskB (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.VirtualPextSigned (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskB (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) imm) <|
    .instr (.VirtualPextSigned (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LBU` expansion. -/
def lbuProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskB (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.VirtualPext (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskB (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) imm) <|
    .instr (.VirtualPext (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LH` expansion. -/
def lhProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskH (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.VirtualPextSigned (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskH (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) imm) <|
    .instr (.VirtualPextSigned (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LHU` expansion. -/
def lhuProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskH (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.VirtualPext (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskH (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) imm) <|
    .instr (.VirtualPext (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LW` expansion. -/
def lwProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskW (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.VirtualPextSigned (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskW (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) imm) <|
    .instr (.VirtualPextSigned (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `MULH` expansion. -/
def mulhProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMovsign (.vreg (BitVec.ofNat 7 40)) (.xreg rs1)) <|
    .instr (.VirtualMovsign (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs1)) <|
    .instr (.MULHU (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (.xreg rs2)) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.ADD (.xreg rd) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `MULHSU` expansion. -/
def mulhsuProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMovsign (.vreg (BitVec.ofNat 7 40)) (.xreg rs1)) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (1 : BitVec 12)) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MULHU (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.xreg rs2)) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.SLTU (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ADD (.xreg rd) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `REM` expansion. -/
def remProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (BitVec.ofNat 7 40)) advice0) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (.xreg rs1)) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 42)) (.xreg rs2) (.xreg rs2)) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualAssertLTE (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualNegateIf (.xreg rd) (.xreg rs1) (.vreg (BitVec.ofNat 7 43))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `REMU` expansion. -/
def remuProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdvice (.vreg (BitVec.ofNat 7 40)) advice0) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.VirtualAssertLTE (.vreg (BitVec.ofNat 7 40)) (.xreg rs1)) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SB` expansion. -/
def sbProgramAuto (rs1 rs2 : regidx) (imm : BitVec 12) : Program :=
  .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) imm) <|
  .instr (.ANDI (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (-8 : BitVec 12)) <|
  .instr (.LD .normal (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
  .instr (.VirtualWindowMaskB (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
  .instr (.ANDN (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
  .instr (.VirtualShiftDataB (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
  .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
  .instr (.SD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
  .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SH` expansion. -/
def shProgramAuto (rs1 rs2 : regidx) (imm : BitVec 12) : Program :=
  .instr (.VirtualAssertHalfwordAlignment rs1 imm (ExceptionType.E_SAMO_Addr_Align ())) <|
  .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) imm) <|
  .instr (.ANDI (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (-8 : BitVec 12)) <|
  .instr (.LD .normal (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
  .instr (.VirtualWindowMaskH (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
  .instr (.ANDN (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
  .instr (.VirtualShiftDataH (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
  .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
  .instr (.SD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
  .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SLL` expansion. -/
def sllProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.MUL (.xreg rd) (.xreg rs1) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SLLI` expansion. -/
def slliProgramAuto (rd rs1 : regidx) (shamt : BitVec 6) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMULI (.xreg rd) (.xreg rs1) (slliMultiplier shamt)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRA` expansion. -/
def sraProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.VirtualSRA (.xreg rd) (.xreg rs1) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRAI` expansion. -/
def sraiProgramAuto (rd rs1 : regidx) (shamt : BitVec 6) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSRAI (.xreg rd) (.xreg rs1) (sraiBitmask shamt)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRL` expansion. -/
def srlProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.VirtualSRL (.xreg rd) (.xreg rs1) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRLI` expansion. -/
def srliProgramAuto (rd rs1 : regidx) (shamt : BitVec 6) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSRLI (.xreg rd) (.xreg rs1) (srliBitmask shamt)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SW` expansion. -/
def swProgramAuto (rs1 rs2 : regidx) (imm : BitVec 12) : Program :=
  .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_SAMO_Addr_Align ())) <|
  .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) imm) <|
  .instr (.ANDI (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (-8 : BitVec 12)) <|
  .instr (.LD .normal (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
  .instr (.VirtualWindowMaskW (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
  .instr (.ANDN (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
  .instr (.VirtualShiftDataW (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
  .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
  .instr (.SD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
  .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SLLIW` expansion. -/
def slliwProgramAuto (rd rs1 : regidx) (shamt : BitVec 5) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualMULIW (.xreg rd) (.xreg rs1) (BitVec.ofNat 64 (2 ^ shamt.toNat))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRLIW` expansion. -/
def srliwProgramAuto (rd rs1 : regidx) (shamt : BitVec 5) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSRLIW (.xreg rd) (.xreg rs1) ((1 <<< 32) - (1 <<< shamt.toNat))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRAIW` expansion. -/
def sraiwProgramAuto (rd rs1 : regidx) (shamt : BitVec 5) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSRAIW (.xreg rd) (.xreg rs1) ((1 <<< 32) - (1 <<< shamt.toNat))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SLLW` expansion. -/
def sllwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualPow2W (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.MULW (.xreg rd) (.xreg rs1) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRLW` expansion. -/
def srlwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualShiftRightBitmaskW (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.VirtualSRLW (.xreg rd) (.xreg rs1) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `SRAW` expansion. -/
def srawProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualShiftRightBitmaskW (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.VirtualSRAW (.xreg rd) (.xreg rs1) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `LWU` expansion. -/
def lwuProgramAuto (rd rs1 : regidx) (imm : BitVec 12) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskW (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.VirtualPext (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 imm (ExceptionType.E_Load_Addr_Align ())) <|
    .instr (.VirtualAlignAddr (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) imm) <|
    .instr (.LD .normal (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualWindowMaskW (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) imm) <|
    .instr (.VirtualPext (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `DIVUW` expansion. -/
def divuwProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 40)) (.xreg rs1)) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.VirtualAdvice (.vreg (BitVec.ofNat 7 42)) advice0) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.VirtualAssertLTE (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualAssertValidDiv0 (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `DIVW` expansion. -/
def divwProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.xreg rs1)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.VirtualAdvice (.vreg (BitVec.ofNat 7 42)) advice0) <|
    .instr (.VirtualAssertValidDiv0 (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 47)) (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualAssertLTE (.vreg (BitVec.ofNat 7 47)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 47)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 47))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (BitVec.ofNat 7 47)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 42))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `REMUW` expansion. -/
def remuwProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 40)) (.xreg rs1)) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.VirtualAdvice (.vreg (BitVec.ofNat 7 42)) advice0) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.VirtualAssertLTE (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 42))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `REMW` expansion. -/
def remwProgramAuto (rd rs1 rs2 : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.ADDI (.xreg (regidx.Regidx 0)) (.xreg (regidx.Regidx 0)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.xreg rs1)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.VirtualAdvice (.vreg (BitVec.ofNat 7 42)) advice0) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.VirtualNegateIf (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.VirtualAssertMulUNoOverflow (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualAssertLTE (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualAssertValidUnsignedRemainder (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualNegateIf (.xreg rd) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 45))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOSWAPW` expansion. -/
def amoswapwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 41)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 44))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 40)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.xreg rs2) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 43))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOADDW` expansion. -/
def amoaddwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 43)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 42)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOANDW` expansion. -/
def amoandwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 43)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 42)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOORW` expansion. -/
def amoorwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.OR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 43)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.OR (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 42)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOXORW` expansion. -/
def amoxorwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 43)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 42)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMINW` expansion. -/
def amominwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 44)) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.SLT (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 44)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 45)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 43)) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.SLT (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 44)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMAXW` expansion. -/
def amomaxwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 44)) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.SLT (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 44)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 45)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 43)) (.xreg rs2)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.SLT (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 44)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMINUW` expansion. -/
def amominuwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 44)) (.xreg rs2)) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.SLTU (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 44)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 45)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 43)) (.xreg rs2)) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.SLTU (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 44)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMAXUW` expansion. -/
def amomaxuwProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 43)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 44)) (.xreg rs2)) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.SLTU (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 44)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 45)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 46)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 46))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 45)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41))) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAssertWordAlignment rs1 (0 : BitVec 12) (ExceptionType.E_SAMO_Addr_Align ())) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (slliMultiplier 3)) <|
    .instr (.VirtualShiftRightBitmask (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.VirtualSRL (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 43)) (.xreg rs2)) <|
    .instr (.VirtualZeroExtendWord (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.SLTU (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.ORI (.vreg (BitVec.ofNat 7 44)) (.xreg (regidx.Regidx 0)) (-1 : BitVec 12)) <|
    .instr (.VirtualSRLI (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (srliBitmask 32)) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.VirtualPow2 (.vreg (BitVec.ofNat 7 45)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 45))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 44))) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ANDI (.vreg (BitVec.ofNat 7 44)) (.xreg rs1) (-8 : BitVec 12)) <|
    .instr (.SD (.vreg (BitVec.ofNat 7 44)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.VirtualSignExtendWord (.xreg rd) (.vreg (BitVec.ofNat 7 40))) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOSWAPD` expansion. -/
def amoswapdProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SD (.xreg rs1) (.xreg rs2) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SD (.xreg rs1) (.xreg rs2) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOADDD` expansion. -/
def amoadddProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOANDD` expansion. -/
def amoanddProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.AND (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOORD` expansion. -/
def amoordProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.OR (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.OR (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOXORD` expansion. -/
def amoxordProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 42)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 42)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.XOR (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMIND` expansion. -/
def amomindProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLT (.vreg (BitVec.ofNat 7 42)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLT (.vreg (BitVec.ofNat 7 41)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 42)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMAXD` expansion. -/
def amomaxdProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLT (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLT (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 42)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMINUD` expansion. -/
def amominudProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLTU (.vreg (BitVec.ofNat 7 42)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLTU (.vreg (BitVec.ofNat 7 41)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 42)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AMOMAXUD` expansion. -/
def amomaxudProgramAuto (rd rs1 rs2 : regidx) : Program :=
  if isX0 rd then
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 41)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLTU (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.xreg rs2)) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 43)) (.xreg rs2) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 43)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 43))) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 42)) (0 : BitVec 12)) <|
    .instr (.ADDI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.LD .amo (.vreg (BitVec.ofNat 7 40)) (.xreg rs1) (0 : BitVec 12)) <|
    .instr (.SLTU (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.xreg rs2)) <|
    .instr (.SUB (.vreg (BitVec.ofNat 7 42)) (.xreg rs2) (.vreg (BitVec.ofNat 7 40))) <|
    .instr (.MUL (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 42)) (.vreg (BitVec.ofNat 7 41))) <|
    .instr (.ADD (.vreg (BitVec.ofNat 7 41)) (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 42))) <|
    .instr (.SD (.xreg rs1) (.vreg (BitVec.ofNat 7 41)) (0 : BitVec 12)) <|
    .instr (.ADDI (.xreg rd) (.vreg (BitVec.ofNat 7 40)) (0 : BitVec 12)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AdviceLB` expansion. -/
def advicelbProgramAuto (rd : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.VirtualAdviceLoad (.vreg (BitVec.ofNat 7 40)) advice0) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (slliMultiplier 56)) <|
    .instr (.VirtualSRAI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (sraiBitmask 56)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdviceLoad (.xreg rd) advice0) <|
    .instr (.VirtualMULI (.xreg rd) (.xreg rd) (slliMultiplier 56)) <|
    .instr (.VirtualSRAI (.xreg rd) (.xreg rd) (sraiBitmask 56)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AdviceLD` expansion. -/
def adviceldProgramAuto (rd : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.VirtualAdviceLoad (.vreg (BitVec.ofNat 7 40)) advice0) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdviceLoad (.xreg rd) advice0) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AdviceLH` expansion. -/
def advicelhProgramAuto (rd : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.VirtualAdviceLoad (.vreg (BitVec.ofNat 7 40)) advice0) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (slliMultiplier 48)) <|
    .instr (.VirtualSRAI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (sraiBitmask 48)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdviceLoad (.xreg rd) advice0) <|
    .instr (.VirtualMULI (.xreg rd) (.xreg rd) (slliMultiplier 48)) <|
    .instr (.VirtualSRAI (.xreg rd) (.xreg rd) (sraiBitmask 48)) <|
    .done RETIRE_SUCCESS

/-- Auto-generated from the Rust `AdviceLW` expansion. -/
def advicelwProgramAuto (rd : regidx) (advice0 : BitVec 64) : Program :=
  if isX0 rd then
    .instr (.VirtualAdviceLoad (.vreg (BitVec.ofNat 7 40)) advice0) <|
    .instr (.VirtualMULI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (slliMultiplier 32)) <|
    .instr (.VirtualSRAI (.vreg (BitVec.ofNat 7 40)) (.vreg (BitVec.ofNat 7 40)) (sraiBitmask 32)) <|
    .done RETIRE_SUCCESS
  else
    .instr (.VirtualAdviceLoad (.xreg rd) advice0) <|
    .instr (.VirtualMULI (.xreg rd) (.xreg rd) (slliMultiplier 32)) <|
    .instr (.VirtualSRAI (.xreg rd) (.xreg rd) (sraiBitmask 32)) <|
    .done RETIRE_SUCCESS

end JoltISA

-- generated 53 expansion program(s)
