import JoltBytecode.InstructionEquivalence.AtomicFamily.Common
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoaddd
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoaddw
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoandd
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoandw
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoord
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoorw
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoxord
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoxorw
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoswapd
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amoswapw
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amomind
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amominw
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amominud
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amominuw
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amomaxd
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amomaxw
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amomaxud
import JoltBytecode.InstructionEquivalence.AtomicFamily.Amomaxuw

/-!
# Atomic-family theorem statement aggregate

This file preserves the old import surface while the per-instruction AMO
statements live in individual files.
-/
